# Use for generating CHANGELOG
builds:
  - binary: check-lastlog
    skip: true
release:
  github:
    owner: kazeburo
    name: check-lastlog
  extra_files:
    - glob: "build/*.zip"
    - glob: "build/*_checksums.txt"