name: release
on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set tag to environment variable
        run: echo ::set-env name=VERSION::${GITHUB_REF#refs/*/}

      - name: Build with xgo
        uses: crazy-max/ghaction-xgo@v1
        with:
          xgo_version: latest
          go_version: 1.15.x
          dest: build
          prefix: check-lastlog
          targets: linux/amd64,linux/arm64
          v: true
          x: false
          ldflags: -s -w -X main.version=${{ env.VERSION }}

      - name: Check build dir
        run: ls -lR build

      - name: Zip binaries
        run: |
          cd build
          for file in ./* ; do mkdir $(echo ${file}|awk -F- '{print "check-lastlog_"$(NF-1)"_"$(NF)}') && cp ${file} $(echo ${file}|awk -F- '{print "check-lastlog_"$(NF-1)"_"$(NF)}')/check-lastlog && zip $(echo ${file}|awk -F- '{print "check-lastlog_"$(NF-1)"_"$(NF)}').zip $(echo ${file}|awk -F- '{print "check-lastlog_"$(NF-1)"_"$(NF)}')/check-lastlog ../README.md ../LICENSE; done
          ls -lR ./

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}