name: release
on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build with xgo
        uses: crazy-max/ghaction-xgo@v1
        with:
          xgo_version: latest
          go_version: 1.15
          dest: build
          prefix: check-lastlog
          targets: linux/amd64,linux/arm64
          v: true
          x: false
          ldflags: -s -w -X main.version=${{ github.ref }}

      - name: tmp
        run: ls -lR build